### ISSUE TITLE
Twitter link is not working

### ISSUE THREAD

**Issue by Anuj-malviya0** [kushagrasarathe/beginners-resources#5]
## While opening your twitter page it says this account doesn't exist
![image](https://user-images.githubusercontent.com/75200824/180652428-8d46afcc-386b-4fa8-8110-cae1c23629fe.png)

**Comment by kushagrasarathe** [comment]
Hey @Anuj-malviya0 I changed my twitter username and forgot to update it here. Thanks for pointing it out, I'll update it with new username https://twitter.com/kushagrasarathe
